### ISSUE TITLE
Error 111

### ISSUE THREAD

**Issue by KSmokvin** [fias-api/jquery#6]
Здравствуйте!
Сегодня перестал работать Плагин Kladr.
Консоль выдаёт попытку запроса к адресу вроде: 

> http://kladr-api.ru/api.php?callback=jQuery111108488397302570003_1564058831863&oneString=true&withParent=true&limit=10&query=Москва&_=1564058831874

Который приводит к ошибке:

> connection to 10.0.0.17:9312 failed (errno=111, msg=Connection refused)

Заменил плагин Kladr на Fias. Ошибка у нового плагина аналогичная. 

Скачал examples с гитхаб. Примеры всё ещё ведут путь к kladr плагину (которого уже нет в корне), переписал на путь на Fias. Но там аналогичная ошибка (и с локальной машины и с хостинга).

На самом же сайте http://kladr-api.ru примеры работают.

Описание ошибки в документации не нашёл. 
Подскажите, пожалуйста, что не так.

**UPD:** Проблема именно с onestring
Примеры на сайте http://kladr-api.ru которые используют onestring тоже не работают.

**Comment by garakh** [comment]
Здравствуйте, сегодня действительно была проблема с полнотекстовым поиском.На данный момент она устранена. 25.07.2019, 15:59, "KSmokvin" <notifications@github.com>:Здравствуйте!Сегодня перестал работать Плагин Kladr.Консоль выдаёт попытку запроса к адресу вроде:http://kladr-api.ru/api.php?callback=jQuery111108488397302570003_1564058831863&oneString=true&withParent=true&limit=10&query=Москва&_=1564058831874Который приводит к ошибке:connection to 10.0.0.17:9312 failed (errno=111, msg=Connection refused)Заменил плагин Kladr на Fias. Ошибка у нового плагина аналогичная.Скачал examples с гитхаб. Примеры всё ещё ведут путь к kladr плагину (которого уже нет в корне), переписал на путь на Fias. Но там аналогичная ошибка (и с локальной машины и с хостинга).На самом же сайте http://kladr-api.ru примеры работают.Описание ошибки в документации не нашёл.Подскажите, пожалуйста, что не так.—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.  ---Илья ГарахПраймпикс+7(952)259-2014г. Архангельск
